# Generated by Django 4.2.6 on 2025-04-14 21:12

import chat_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_message_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertiseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_app.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_psych_student', models.BooleanField(default=False)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('anonymous_id', models.CharField(default=chat_app.models.generate_anonymous_id, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_students', to='chat_app.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_category', models.CharField(choices=[('inappropriate', 'Inappropriate Content'), ('harassment', 'Harassment'), ('spam', 'Spam'), ('other', 'Other')], default='other', max_length=20)),
                ('reason_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat_app.message')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.userprofile')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to='chat_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PsychologyStudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('school_year', models.PositiveSmallIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('expertise_areas', models.ManyToManyField(blank=True, to='chat_app.expertisearea')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psych_student_profile', to='chat_app.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.userprofile'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='normal_user',
            field=models.ForeignKey(limit_choices_to={'is_psych_student': False, 'is_supervisor': False}, on_delete=django.db.models.deletion.CASCADE, related_name='user_chats', to='chat_app.userprofile'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='psych_student',
            field=models.ForeignKey(limit_choices_to={'is_psych_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='psych_chats', to='chat_app.userprofile'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='supervisor_access',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_supervisor': True}, related_name='supervised_chats', to='chat_app.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='chatsession',
            unique_together={('psych_student', 'normal_user')},
        ),
    ]
