# Generated by Django 4.2.6 on 2025-05-25 20:12

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
    ]
