# Generated by Django 4.2.6 on 2025-05-26 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_alter_message_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorStudentChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(limit_choices_to={'is_psych_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to='chat_app.userprofile')),
                ('supervisor', models.ForeignKey(limit_choices_to={'is_supervisor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_sessions', to='chat_app.userprofile')),
            ],
            options={
                'ordering': ['-last_message_time'],
                'unique_together': {('supervisor', 'student')},
            },
        ),
    ]
