# Generated by Django 4.2.6 on 2025-05-26 21:42

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_supervisorstudentchatsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperVisorStudentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_cryptography.fields.encrypt(models.TextField())),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_app.supervisorstudentchatsession')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_supervisor_student_messages', to='chat_app.userprofile')),
            ],
        ),
    ]
