# Generated by Django 4.2.6 on 2025-05-27 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_supervisorstudentmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_flagged',
        ),
        migrations.RemoveField(
            model_name='report',
            name='message',
        ),
        migrations.AddField(
            model_name='report',
            name='chat_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat_app.chatsession'),
            preserve_default=False,
        ),
    ]
